name: "Release follow-up"
on:
  release:
    types: [published]

jobs:
  create-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate homebrew formula
        run: make homebrew-formula-generate

      - uses: actions/upload-artifact@v2
        with:
          path: "./dist/syft.rb"

  test-formula-linux:
    runs-on: ubuntu-latest
    needs: create-homebrew-formula
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: "dist"

      - name: Test homebrew formula
        run: make homebrew-formula-test

  test-formula-mac:
    runs-on: macos-latest
    needs: create-homebrew-formula
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: "dist"

      - name: Test homebrew formula
        run: make homebrew-formula-test

  publish-formula:
    runs-on: ubuntu-latest
    needs: [ test-formula-linux, test-formula-mac ]
    steps:
      - uses: actions/download-artifact@v2

      - name: Publish updated homebrew formula
        run: homebrew-formula-publish

  update_version_check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update version check file
        run: make version-check-update
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLBOX_AWS_SECRET_ACCESS_KEY }}
